# mysql server seeded with databases from dump files in the folder ./mysql
# The seeding only happens on the first start when the volume is created.
# If you need to reset the seeding, you need to "run docker compose down -v" to delete the volume
services:
  rpg_mysql:
    image: mysql:9.5.0
    container_name: rpg_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - rpg_mysql:/var/rpg_mysql
      - ./rpg_mysql:/docker-entrypoint-initdb.d
    hostname: rpg_mysql
volumes:
  rpg_mysql:
    driver: local